languageCode = 'en-us'
title = 'localh0st.run'
#theme = ['hugo-video','classless-blog'] 
theme = ['hugo-video','fuji'] 
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[menu]
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
[[menu.nav]]
name = "Posts"
url = "/post/"
weight = 2
[[menu.nav]]
name = "About"
url = "/about/"
weight = 3

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Enable user to embed HTML snippets in Markdown content
[markup.highlight]
codeFences = true # Disable Hugo's code highlighter

sourceURL = "https://localh0st.run"

baseURL = 'https://localh0st.run'
baseurl = "https://localh0st.run"